# Generated by Django 2.2 on 2020-05-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='genre',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='mean',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronounce',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
