# Generated by Django 2.2 on 2020-05-10 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200510_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='mean',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='pronounce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
